version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly" # Update GitHub Actions dependencies monthly
    labels:
      - "ci-dependencies"
      - "dependabot-auto-merge"
