- name: "auto-merge"
  color: "#0E8A16"
  description: "Automatically merge approved PRs"

- name: "bug"
  color: "#d73a4a"
  description: "Something isn’t working"

- name: "enhancement"
  color: "#a2eeef"
  description: "New feature or request"

- name: "documentation"
  color: "#0075ca"
  description: "Improvements or additions to documentation"

- name: "dependabot-auto-merge"
  color: "#f9d0c4"
  description: "Dependabot PRs that can be auto-merged"

- name: "pre-commit-auto-update"
  color: "#f2c94c"
  description: "Pre-commit hooks auto-update PRs"

- name: "auto-merge-dependabot"
  color: "#f2c94c"
  description: "Auto-merge Dependabot PRs"

- name: "ci-dependencies"
  color: "#d4c5f9"
  description: "Dependencies related to CI/CD"

- name: "auto-merge-pre-commit"
  color: "#d4c5f9"
  description: "Auto-merge pre-commit hooks update PRs"

- name: "invalid"
  color: "#e4e669"
  description: "This doesn’t seem right"

- name: "question"
  color: "#d876e3"
  description: "Further information is requested"

- name: "wontfix_it"
  color: "#000000"
  description: "This will not be worked on"
  from_name: "wontfix"