name: Metrics

on:
  schedule:
    - cron: "0 0 * * *" # Runs at 00:00 UTC every day
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Generate Language Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.CLASSIC_TOKEN }}
          filename: metrics-languages.svg
          base: ""
          config_order: languages
          plugin_languages: yes
          plugin_languages_sections: most-used, recently-used
          plugin_languages_recent_load: 400
          plugin_languages_recent_days: 14
          plugin_languages_limit: 8
          plugin_languages_other: yes
          plugin_languages_colors: github
          plugin_languages_details: percentage
          plugin_languages_threshold: 2%

      - name: Generate Repository Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.CLASSIC_TOKEN }}
          filename: metrics-repositories.svg
          base: ""
          config_order: repositories
          plugin_repositories: yes
          plugin_repositories_pinned: 6
          plugin_repositories_featured: Damianko135/Damianko135
          plugin_repositories_starred: 10
          plugin_repositories_random: 5
          plugin_repositories_forks: yes
          repositories_batch: 10

      - name: Generate Contribution Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.CLASSIC_TOKEN }}
          filename: metrics-contributions.svg
          base: ""
          plugin_contributors: yes
          plugin_contributors_sections: commits, issues, pull-requests, reviews

      - name: Generate Activity Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.CLASSIC_TOKEN }}
          filename: metrics-activity.svg
          base: ""
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 14

      - name: Generate Achievements Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.CLASSIC_TOKEN }}
          filename: metrics-achievements.svg
          base: ""
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_threshold: B

      - name: Generate Additional Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.CLASSIC_TOKEN }}
          filename: metrics-additional.svg
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_charts: yes

      - name: Commit and Push Metrics
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "Update README with new metrics"
          git push
