# This is a sample hardware configuration file.
# You should replace this with your actual hardware configuration
# generated by nixos-generate-config.

{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  # Boot configuration
  boot = {
    initrd = {
      availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
      kernelModules = [ ];
    };
    kernelModules = [ "kvm-intel" ]; # Change to "kvm-amd" for AMD processors
    extraModulePackages = [ ];
  };

  # Filesystems - REPLACE WITH YOUR ACTUAL FILESYSTEM CONFIGURATION
  fileSystems."/" = {
    device = "/dev/disk/by-uuid/YOUR-ROOT-UUID-HERE";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/YOUR-BOOT-UUID-HERE";
    fsType = "vfat";
  };

  # Swap - REPLACE WITH YOUR ACTUAL SWAP CONFIGURATION
  swapDevices = [
    { device = "/dev/disk/by-uuid/YOUR-SWAP-UUID-HERE"; }
  ];

  # Hardware configuration
  hardware = {
    # CPU
    cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
    # For AMD: cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
    
    # Enable firmware updates
    enableRedistributableFirmware = true;
    
    # Graphics
    opengl = {
      enable = true;
      driSupport = true;
      driSupport32Bit = true;
    };
    
    # Nvidia (uncomment if you have Nvidia GPU)
    # nvidia = {
    #   modesetting.enable = true;
    #   powerManagement.enable = false;
    #   powerManagement.finegrained = false;
    #   open = false;
    #   nvidiaSettings = true;
    #   package = config.boot.kernelPackages.nvidiaPackages.stable;
    # };
  };

  # Power management
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  
  # Enable thermald for Intel CPUs
  services.thermald.enable = lib.mkDefault true;
  
  # Networking
  networking.useDHCP = lib.mkDefault true;
  
  # High-DPI display support
  # hardware.video.hidpi.enable = lib.mkDefault true;
  
  # This value determines the NixOS release from which the default
  # settings for stateful data, like file locations and database versions
  # on your system were taken. It's perfectly fine and recommended to leave
  # this value at the release version of the first install of this system.
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}