name: Dependabot Golang Auto-Merge

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: dependabot-auto-merge-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    if: >
      github.actor == 'dependabot[bot]' &&
      contains(github.event.pull_request.labels.*.name, 'dependabot-auto-merge') &&
      contains(github.event.pull_request.labels.*.name, 'golang-dependencies')

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "^1.20.x"

      - name: Validate PR is Up-to-Date
        run: |
          git fetch origin ${{ github.event.pull_request.base.ref }}
          git checkout ${{ github.event.pull_request.head.ref }}
          git merge --no-edit origin/${{ github.event.pull_request.base.ref }}

      - name: Tidy Dependencies
        run: go mod tidy

      - name: Install Dependencies
        run: go mod download

      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: ./...

      - name: Run Golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          args: run

      - name: Run Tests
        run: go test ./... -v

      - name: Validate Checks
        run: |
          gh pr checks "$PR_URL"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}

      - name: Enable Auto-Merge
        run: |
          gh pr merge --auto --merge "$PR_URL"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}

      - name: Post Success Message
        run: |
          echo "Dependabot PR #${{ github.event.pull_request.number }} processed successfully."
